runtime: nodejs
env: flex
service: backend

env_variables:
  NODE_ENV: "production"
  ANOTHER_ENV_VARIABLE: "value"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cpu_utilization:
    target_utilization: 0.5
