steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/backend-container', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/backend-container']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--image-url', 'eu.gcr.io/$PROJECT_ID/backend-container']
images: ['eu.gcr.io/$PROJECT_ID/backend-container']

